export const LOAD_DATA = "LOAD_DATA";
export const LOAD_TODOS_SUCCESS = "LOAD_TODOS_SUCCESS";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";

export const TOGGLE = "TOGGLE";
export const TOGGLE_SUCCESS = "TOGGLE_SUCCESS";

export const EDIT_TODO = "EDIT_TODO";
export const EDIT_TODO_SUCCESS = "EDIT_TODO_SUCCESS";
